_wandb:
    value:
        cli_version: 0.23.1
        e:
            blyavzpxj43rsf01qjau5ar04ww6gc4i:
                args:
                    - -pe
                    - "0.2"
                codePath: Tarefa_1/main.py
                codePathLocal: main.py
                cpu_count: 4
                cpu_count_logical: 4
                disk:
                    /:
                        total: "58581958656"
                        used: "44398534656"
                email: hugosachim@ua.pt
                executable: /usr/bin/python3
                git:
                    commit: 50310717a372bdce694b1300e5228190f1f5b68c
                    remote: https://github.com/HugoSachim/savi-2025-2026-trabalho2-grupoX.git
                host: hogu-laptop
                memory:
                    total: "8134238208"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/Tarefa_1/./main.py
                python: CPython 3.12.3
                root: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/Tarefa_1
                startedAt: "2025-12-17T22:27:09.598979Z"
                writerId: blyavzpxj43rsf01qjau5ar04ww6gc4i
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 64
dataset_folder:
    value: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/datasets/mnist
experiment_full_name:
    value: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/datasets/savi_experiments/2025-12-17
experiment_path:
    value: /home/hogu/Desktop/savi-2025-2026-trabalho2-grupoX/datasets/savi_experiments
num_epochs:
    value: 10
percentage_examples:
    value: 0.2
resume_training:
    value: false
